# .rubocop.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'config/*'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'bin/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: true
  Exclude:
    - 'app/controllers/**'

Rails/I18nLocaleTexts:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/BlockDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/controllers/**/*_spec.rb'
    - 'spec/features/**/*_spec.rb'
    - 'spec/services/**/*_spec.rb'
    - 'spec/*_helper.rb'
    - 'spec/models/**/*_spec.rb'

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'app/controllers/oauth_callbacks_controller.rb'
    - 'app/models/ability.rb'
    - 'app/controllers/answers_controller.rb'
