# .rubocop.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'config/*'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'bin/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/controllers/**/*_spec.rb'
    - 'spec/features/**/*_spec.rb'
